[env]
platform = ststm32
board = genericSTM32F446RE
framework = stm32cube

; change microcontroller
board_build.mcu = stm32f446ret6

; change MCU frequency
board_build.f_cpu = 160000000L

upload_protocol = stlink

[env:genericSTM32F446RE]
build_type = release

[env:genericSTM32F446RE_debug]
build_type = debug
build_flags =
    -DDEBUG_LOG_ENABLED=1
